name: Build and Push Docker Images

on:
  push:
    branches: [ "master" ]

jobs:
  # Check for changes
  changes:
    runs-on: ubuntu-latest
    outputs:
      ai: ${{ steps.filter.outputs.ai }}
      backend: ${{ steps.filter.outputs.backend }}
      web: ${{ steps.filter.outputs.web }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            ai: - 'ai-service/**'
            backend: - 'backend-node/**'
            web: - 'web-app/**'

  # Build do AI Service 
  build-ai:
    needs: changes
    if: ${{ needs.changes.outputs.ai == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./ai-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/attendance-ai:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Build do Backend 
  build-backend:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./backend-node
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/attendance-backend-node:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Build do Web App 
  build-web:
    needs: changes
    if: ${{ needs.changes.outputs.web == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./web-app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/attendance-web-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max